name: Deploy Node Modules

on:
  push:
    branches:
      - main

jobs:
  install-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js v22
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Buat package.json kalau belum ada
      run: |
        if [ ! -f package.json ]; then
          npm init -y
        fi

    - name: Baca file .dep.modsy dan install dependensi
      run: |
        while read -r line || [[ -n "$line" ]]; do
          pkg=$(echo "$line" | sed 's/#.*//g' | xargs)
          if [ ! -z "$pkg" ]; then
            echo "Menginstal: $pkg"
            npm install "$pkg"
          fi
        done < .dep.modsy

    - name: Push node_modules dan package.json ke repo
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add node_modules package.json package-lock.json
        git commit -m "auto: update deps from .dep.modsy" || echo "No changes"
        git push
